apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  selector:
    app: chat-app
  ports:
  - protocol: TCP
    port: 3000 # External port exposed to users (localhost:3010)
    targetPort: 3000 # Internal port inside the container where the app is running
  type: NodePort # Exposes the service as a NodePort for local access
